⚡ Fix attribute error caused by rebased test
* Updated `test_build.py` to fix a `AttributeError: module has no attribute 'subprocess'` crash caused by a recently merged test that was still mocking `subprocess.run` instead of the newly implemented `asyncio.create_subprocess_exec`.